[package]
name = "tachtalk"
version = "0.1.0"
authors = ["docwilco"]
edition = "2021"
resolver = "2"
rust-version = "1.71"

[profile.release]
opt-level = "s"

[profile.dev]
debug = true    # Symbols are nice and they don't increase the size on Flash
opt-level = "z"

[dependencies]
log = { version = "0.4", default-features = false }
esp-idf-svc = { version = "0.49", default-features = false }
esp-idf-hal = { version = "0.44" }
esp-idf-sys = { version = "0.35" }
embedded-svc = "0.28"
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
smart-leds = "0.4"
ws2812-esp32-rmt-driver = "0.9"

[build-dependencies]
embuild = "0.32"
