[package]
name = "tachtalk-shift-lights-lib"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
num-integer.workspace = true
rgb.workspace = true
serde.workspace = true
smallvec.workspace = true
