[package]
name = "tachtalk-capture-decode"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true

[[bin]]
name = "tachtalk-capture-decode"
path = "src/main.rs"

[dependencies]
clap.workspace = true
tachtalk-capture-format.workspace = true
