[package]
name = "tachtalk-benchmark-client"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true

[[bin]]
name = "tachtalk-benchmark"
path = "src/main.rs"

[dependencies]
clap.workspace = true
